type: google.api.service
config_version: 3

http:
  rules:
    - selector: message.EchoService.Echo
      get: /echo
    - selector: message.EchoService.Echo2
      post: /echo2
      # 不要漏掉了双引号
      body: "*"
    - selector: message.EchoService.Echo3
      delete: /echo3
      body: "*"
